### ISSUE TITLE
CAN Address 2 multiple use

### ISSUE THREAD

**Issue by tcjinaz** [Pridetronics/InfiniteRechargeV3#7]
CAN address 2 is used for both RIGHT_DRIVE_MOTOR_LEAD and SHOOTER_MOTOR_CAN_ADDRESS

https://github.com/Pridetronics/InfiniteRechargeV3/blob/master/src/main/java/frc/robot/Constants.java

**Comment by mzakocs** [comment]
This was fixed a while ago on me and euans branch, we just need to push to master
